apiVersion: v1
entries:
  otoroshi:
  - apiVersion: v3
    appVersion: 1.5.3
    created: "2022-02-14T13:29:30.864635+01:00"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: 560fbc62853ebcbdea1474013d5c3ea0d9c62a61964265295311d1f15bc5f717
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.3.tgz
    version: 1.5.3
  - apiVersion: v3
    appVersion: 1.5.2
    created: "2022-02-14T13:29:30.859039+01:00"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: 33be8d43ec7cc787a2bbab634805ba3ff0e83bd2c35a527d3ea0cf368b9d2330
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.2.tgz
    version: 1.5.2
  - apiVersion: v3
    appVersion: 1.5.1
    created: "2022-02-14T13:29:30.851645+01:00"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: 271325c8151da7ec906e6ea51eec9390f84d85b79d78fd931d6d8ecc2e4df2dd
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.1.tgz
    version: 1.5.1
  - apiVersion: v3
    appVersion: 1.5.0
    created: "2022-02-14T13:29:30.84353+01:00"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: e0bffdbb468e094b1c7ef92ab984b734d93d0e4d6d2881ceb5065259d5d3ad0e
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.0.tgz
    version: 1.5.0
  - apiVersion: v3
    appVersion: 1.5.0-rc.4
    created: "2022-02-14T13:29:30.835411+01:00"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: 4bc7a10682d1c014fb0507af24817a7bb95775a728d6243d55beecc249f78c40
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.0-rc.4.tgz
    version: 1.5.0-rc.4
  - apiVersion: v3
    appVersion: 1.5.0-dev
    created: "2022-02-14T13:29:30.827874+01:00"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: e102915f483a70e5e95a4945ef7f34e0273a03f4a03a2c5a7b01b956c3294131
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.0-dev.tgz
    version: 1.5.0-dev
generated: "2022-02-14T13:29:30.82005+01:00"
