apiVersion: v1
entries:
  otoroshi:
  - apiVersion: v3
    appVersion: 1.5.0-dev
    created: "2021-11-16T14:49:39.617445+01:00"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: e3b2bfcb007ec6dbc84088084c805374f515a95082721d672afe66c2b60cbf2a
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.0.0.tgz
    version: 1.0.0
generated: "2021-11-16T14:49:39.610225+01:00"
