version: '3'
services:

  ########################################################################################
  ########################################################################################
  ########################################################################################

  leader:
    # build: ./otoroshi
    image: maif/otoroshi:1.5.13-jdk11
    networks:
      - cluster
    environment: 
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - OTOROSHI_CLUSTER_MODE=leader
      - OTOROSHI_INITIAL_ADMIN_PASSWORD=password
      - OTOROSHI_STORAGE=lettuce
      - OTOROSHI_REDIS_URL=redis://redis:6379
      - OTOROSHI_CLUSTER_LEADER_NAME=leader
      - OTOROSHI_INSTANCE_TITLE=leader
    expose:
      - 8080
      - 8443
    ports: 
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - redis

########################################################################################
########################################################################################
########################################################################################

  worker-1:
    image: maif/otoroshi:1.5.13-jdk11
    networks:
      - cluster
    environment: 
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - OTOROSHI_CLUSTER_MODE=worker
      - OTOROSHI_INITIAL_ADMIN_PASSWORD=password
      - OTOROSHI_CLUSTER_WORKER_NAME=worker-1
      - OTOROSHI_CLUSTER_LEADER_URL=http://leader:8080
      - OTOROSHI_CLUSTER_LEADER_HOST=otoroshi-api.oto.tools
    expose:
      - 8080
      - 8443
    ports: 
      - "8081:8080"
      - "8444:8443"
    depends_on:
      - leader

  worker-2:
    image: maif/otoroshi:1.5.13-jdk11
    networks:
      - cluster
    environment: 
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - OTOROSHI_CLUSTER_MODE=worker
      - OTOROSHI_INITIAL_ADMIN_PASSWORD=password
      - OTOROSHI_CLUSTER_WORKER_NAME=worker-2
      - OTOROSHI_CLUSTER_LEADER_URL=http://leader:8080
      - OTOROSHI_CLUSTER_LEADER_HOST=otoroshi-api.oto.tools
    expose:
      - 8080
      - 8443
    ports: 
      - "8082:8080"
      - "8445:8443"
    depends_on:
      - leader

########################################################################################
########################################################################################
########################################################################################

  service:
    image: traefik/whoami
    environment:
      - WHOAMI_NAME=service
    expose:
      - 80
    ports:
      - "8091:80"
    networks:
      - cluster

########################################################################################
########################################################################################
########################################################################################

  redis:
    image: redis:4.0.8
    expose:
      - 6379
    networks:
      - cluster
    command: redis-server --appendonly yes
    volumes:
      - ./data/otoroshi-leader-data:/data

########################################################################################
########################################################################################
########################################################################################

networks:
  cluster:
    driver: bridge
    ipam:
      driver: default