version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
    - 9200:9200
    environment:
    - "xpack.security.enabled=false"
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#  cassandra: 
#    image: cassandra:3.11
#    ports:
#    - 7000:7000
#    - 9042:9042
#    environment:
#    - "CASSANDRA_LISTEN_ADDRESS=127.0.0.1"
#  redis: 
#    image: redis:4.0.8
#    ports:
#    - 6379:6379  
#    environment:
#    - "CASSANDRA_LISTEN_ADDRESS=127.0.0.1"    