version: '3'
services:

  ########################################################################################
  ########################################################################################
  ########################################################################################

  leader-zone-1:
    # build: ./otoroshi
    image: eclipse-temurin:11
    command: "java -jar /tmp/otoroshi/otoroshi.jar"
    volumes:
      - "./otoroshi:/tmp/otoroshi"
    networks:
      - relay
      - zone-1
    environment: 
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - OTOROSHI_CLUSTER_MODE=leader
      - OTOROSHI_INITIAL_ADMIN_PASSWORD=password
      - OTOROSHI_STORAGE=lettuce
      - OTOROSHI_REDIS_URL=redis://redis:6379
      - OTOROSHI_CLUSTER_LEADER_NAME=leader-zone-1
      - OTOROSHI_CLUSTER_RELAY_ENABLED=true
      - OTOROSHI_CLUSTER_RELAY_LOCATION_ZONE=zone-1
      - OTOROSHI_CLUSTER_RELAY_EXPOSITION_URL=http://leader-zone-1:8080
      - OTOROSHI_CLUSTER_RELAY_EXPOSITION_HOSTNAME=otoroshi-api.oto.tools
      - OTOROSHI_LOGGERS_OTOROSHI-RELAY-ROUTING=DEBUG
    expose:
      - 8080
      - 8443
    ports: 
      - "8081:8080"
      - "8441:8443"
    depends_on:
      - redis

  ########################################################################################

  leader-zone-2:
    # build: ./otoroshi
    image: eclipse-temurin:11
    command: "java -jar /tmp/otoroshi/otoroshi.jar"
    volumes:
      - "./otoroshi:/tmp/otoroshi"
    networks:
      - relay
      - zone-2
    environment: 
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - OTOROSHI_CLUSTER_MODE=leader
      - OTOROSHI_INITIAL_ADMIN_PASSWORD=password
      - OTOROSHI_STORAGE=lettuce
      - OTOROSHI_REDIS_URL=redis://redis:6379
      - OTOROSHI_CLUSTER_LEADER_NAME=leader-zone-2
      - OTOROSHI_CLUSTER_RELAY_ENABLED=true
      - OTOROSHI_CLUSTER_RELAY_LOCATION_ZONE=zone-2
      - OTOROSHI_CLUSTER_RELAY_EXPOSITION_URL=http://leader-zone-2:8080
      - OTOROSHI_CLUSTER_RELAY_EXPOSITION_HOSTNAME=otoroshi-api.oto.tools
      - OTOROSHI_LOGGERS_OTOROSHI-RELAY-ROUTING=DEBUG
    expose:
      - 8080
      - 8443
    ports: 
      - "8082:8080"
      - "8442:8443"
    depends_on:
      - redis

  ########################################################################################

  leader-zone-3:
    # build: ./otoroshi
    image: eclipse-temurin:11
    command: "java -jar /tmp/otoroshi/otoroshi.jar"
    volumes:
      - "./otoroshi:/tmp/otoroshi"
    networks:
      - relay
      - zone-3
    environment: 
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - OTOROSHI_CLUSTER_MODE=leader
      - OTOROSHI_INITIAL_ADMIN_PASSWORD=password
      - OTOROSHI_STORAGE=lettuce
      - OTOROSHI_REDIS_URL=redis://redis:6379
      - OTOROSHI_CLUSTER_LEADER_NAME=leader-zone-3
      - OTOROSHI_CLUSTER_RELAY_ENABLED=true
      - OTOROSHI_CLUSTER_RELAY_LOCATION_ZONE=zone-3
      - OTOROSHI_CLUSTER_RELAY_EXPOSITION_URL=http://leader-zone-3:8080
      - OTOROSHI_CLUSTER_RELAY_EXPOSITION_HOSTNAME=otoroshi-api.oto.tools
      - OTOROSHI_LOGGERS_OTOROSHI-RELAY-ROUTING=DEBUG
    expose:
      - 8080
      - 8443
    ports: 
      - "8083:8080"
      - "8443:8443"
    depends_on:
      - redis

  ########################################################################################
  ########################################################################################
  ########################################################################################

  worker-zone-1:
    # build: ./otoroshi
    image: eclipse-temurin:11
    command: "java -jar /tmp/otoroshi/otoroshi.jar"
    volumes:
      - "./otoroshi:/tmp/otoroshi"
    networks:
      - zone-1
    environment: 
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - OTOROSHI_CLUSTER_MODE=worker
      - OTOROSHI_INITIAL_ADMIN_PASSWORD=password
      - CLUSTER_WORKER_NAME=worker-zone-1
      - OTOROSHI_CLUSTER_LEADER_URL=http://leader-zone-1:8080
      - CLUSTER_LEADER_HOST=otoroshi-api.oto.tools
      - OTOROSHI_CLUSTER_RELAY_ENABLED=true
      - OTOROSHI_CLUSTER_RELAY_LEADER_ONLY=true
      - OTOROSHI_CLUSTER_RELAY_LOCATION_ZONE=zone-1
      - OTOROSHI_CLUSTER_RELAY_EXPOSITION_URL=http://leader-zone-1:8080
      - OTOROSHI_CLUSTER_RELAY_EXPOSITION_HOSTNAME=otoroshi-api.oto.tools
      - OTOROSHI_LOGGERS_OTOROSHI-RELAY-ROUTING=DEBUG
    expose:
      - 8080
      - 8443
    ports: 
      - "8084:8080"
      - "8444:8443"
    depends_on:
      - leader-zone-1

  ########################################################################################

  worker-zone-2:
    # build: ./otoroshi
    image: eclipse-temurin:11
    command: "java -jar /tmp/otoroshi/otoroshi.jar"
    volumes:
      - "./otoroshi:/tmp/otoroshi"
    networks:
      - zone-2
    environment: 
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - OTOROSHI_CLUSTER_MODE=worker
      - OTOROSHI_INITIAL_ADMIN_PASSWORD=password
      - CLUSTER_WORKER_NAME=worker-zone-2
      - OTOROSHI_CLUSTER_LEADER_URL=http://leader-zone-2:8080
      - CLUSTER_LEADER_HOST=otoroshi-api.oto.tools
      - OTOROSHI_CLUSTER_RELAY_ENABLED=true
      - OTOROSHI_CLUSTER_RELAY_LEADER_ONLY=true
      - OTOROSHI_CLUSTER_RELAY_LOCATION_ZONE=zone-2
      - OTOROSHI_CLUSTER_RELAY_EXPOSITION_URL=http://leader-zone-2:8080
      - OTOROSHI_CLUSTER_RELAY_EXPOSITION_HOSTNAME=otoroshi-api.oto.tools
      - OTOROSHI_LOGGERS_OTOROSHI-RELAY-ROUTING=DEBUG
    expose:
      - 8080
      - 8443
    ports: 
      - "8085:8080"
      - "8445:8443"
    depends_on:
      - leader-zone-2

  ########################################################################################

  worker-zone-3:
    # build: ./otoroshi
    image: eclipse-temurin:11
    command: "java -jar /tmp/otoroshi/otoroshi.jar"
    volumes:
      - "./otoroshi:/tmp/otoroshi"
    networks:
      - zone-3
    environment: 
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - OTOROSHI_CLUSTER_MODE=worker
      - OTOROSHI_INITIAL_ADMIN_PASSWORD=password
      - CLUSTER_WORKER_NAME=worker-zone-3
      - OTOROSHI_CLUSTER_LEADER_URL=http://leader-zone-3:8080
      - CLUSTER_LEADER_HOST=otoroshi-api.oto.tools
      - OTOROSHI_CLUSTER_RELAY_ENABLED=true
      - OTOROSHI_CLUSTER_RELAY_LEADER_ONLY=true
      - OTOROSHI_CLUSTER_RELAY_LOCATION_ZONE=zone-3
      - OTOROSHI_CLUSTER_RELAY_EXPOSITION_URL=http://leader-zone-3:8080
      - OTOROSHI_CLUSTER_RELAY_EXPOSITION_HOSTNAME=otoroshi-api.oto.tools
      - OTOROSHI_LOGGERS_OTOROSHI-RELAY-ROUTING=DEBUG
    expose:
      - 8080
      - 8443
    ports: 
      - "8086:8080"
      - "8446:8443"
    depends_on:
      - leader-zone-3

  ########################################################################################
  ########################################################################################
  ########################################################################################

  service-a:
    image: traefik/whoami
    environment:
      - WHOAMI_NAME=service-a-zone-1
    expose:
      - 80
    ports:
      - "8091:80"
    networks:
      - zone-1

  ########################################################################################
  
  service-b:
    image: traefik/whoami
    environment:
      - WHOAMI_NAME=service-b-zone-2
    expose:
      - 80
    ports:
      - "8092:80"
    networks:
      - zone-2

  ########################################################################################

  service-c:
    image: traefik/whoami
    environment:
      - WHOAMI_NAME=service-c-zone-3
    expose:
      - 80
    ports:
      - "8093:80"
    networks:
      - zone-3

  ########################################################################################

  service-d-zone-1:
    image: traefik/whoami
    environment:
      - WHOAMI_NAME=service-d-zone-1
    expose:
      - 80
    ports:
      - "8094:80"
    networks:
      - zone-1

  ########################################################################################

  service-d-zone-2:
    image: traefik/whoami
    environment:
      - WHOAMI_NAME=service-d-zone-2
    expose:
      - 80
    ports:
      - "8095:80"
    networks:
      - zone-2

  ########################################################################################
  ########################################################################################
  ########################################################################################

  redis:
    image: redis:4.0.8
    expose:
      - 6379
    networks:
      - relay
    command: redis-server --appendonly yes
    volumes:
      - ./data/otoroshi-leader-data:/data

  ########################################################################################
  ########################################################################################
  ########################################################################################

networks:
  relay:
    driver: bridge
    ipam:
      driver: default
      #config:
      #  - subnet: 172.16.239.30/24
  zone-1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.241.31/24
  zone-2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.242.32/24
  zone-3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.243.33/24