name: publish-otoroshi-documentation

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Current version"
      
jobs:
  release-otoroshi:
    name: publish-otoroshi-documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup jdk11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: setup git
        run: | 
          git config --global user.email "otoroshi-bot-github-actions@users.noreply.github.com"
          git config --global user.name "otoroshi-bot-github-actions"
          git config --global --list      
      - name: Setup xvfb for screen 0
        run: |
          Xvfb :1 -screen 0 1600x1200x24 &         
      - name: run-doc-process
        id: run-doc-process
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISPLAY: :1
        run: |
          LOC=$(pwd)
          # TODO: change version in files
          # TODO: node ./scripts/release/change-doc-version-github-action.js
          sh ./scripts/doc.sh all
          # TODO: git commit -am 'publish documentation'
          # TODO: git push origin master
