[package]
name = "oto-mesh"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
hmac = "0.12.1"
hyper = "0.14.24"
hyper-rustls = "0.23.2"
jwt = "0.16.0"
serde = "1.0.152"
serde_json = "1.0.93"
sha2 = "0.10.6"
